// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNnDyafG-pda6G36-ZY5RUcKMt6t2UAw',
    appId: '1:323048737653:web:27a3e580316f001c33613c',
    messagingSenderId: '323048737653',
    projectId: 'scholar-chat-52555',
    authDomain: 'scholar-chat-52555.firebaseapp.com',
    storageBucket: 'scholar-chat-52555.firebasestorage.app',
    measurementId: 'G-DQJ3B7G3PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GJe5R5phjnjwLaUgQA8Zqz51eDF-CLk',
    appId: '1:323048737653:android:08718cc7c7ceae9d33613c',
    messagingSenderId: '323048737653',
    projectId: 'scholar-chat-52555',
    storageBucket: 'scholar-chat-52555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTt2XlrfKeBG6EKoQGh1ZV7-jkzNq0qb0',
    appId: '1:323048737653:ios:cc5e27bfee20ba4d33613c',
    messagingSenderId: '323048737653',
    projectId: 'scholar-chat-52555',
    storageBucket: 'scholar-chat-52555.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTt2XlrfKeBG6EKoQGh1ZV7-jkzNq0qb0',
    appId: '1:323048737653:ios:cc5e27bfee20ba4d33613c',
    messagingSenderId: '323048737653',
    projectId: 'scholar-chat-52555',
    storageBucket: 'scholar-chat-52555.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLNnDyafG-pda6G36-ZY5RUcKMt6t2UAw',
    appId: '1:323048737653:web:9cca62a9cdce897b33613c',
    messagingSenderId: '323048737653',
    projectId: 'scholar-chat-52555',
    authDomain: 'scholar-chat-52555.firebaseapp.com',
    storageBucket: 'scholar-chat-52555.firebasestorage.app',
    measurementId: 'G-M2PZM55Q8C',
  );
}
